export const AGENT_BENCHMARK = {
  name: 'PACE Synthetic Benchmark v1',
  seed: 2609,
  scope: { scenarioGroups: 30, trainPhrases: 600, costItems: 180, controlledAnomalies: 45, classes: 6 },
  model: 'Domain ontology + character 2–5 gram TF-IDF centroid model',
  splitAudit: {
    strategy: '표현군 단위 Hold-out · seed 2609',
    trainFamilies: 24,
    testFamilies: 36,
    familyOverlap: 0,
    exactRecordOverlap: 0,
    note: '학습·평가의 기본 표현군은 분리했으며 도메인 용어사전은 모델 구성요소로 양쪽에 공통 적용했습니다.',
  },
  metrics: {
    mappingAccuracy: 0.9167,
    mappingMacroF1: 0.9189,
    evidenceLinkAccuracy: 0.8545,
    exceptionPrecision: 0.9,
    exceptionRecall: 1,
    exceptionF1: 0.9474,
    falseAutoClear: 0,
    endToEndAccuracy: 0.8611,
  },
  limitations: [
    '실제 기항 스케줄이나 기업 문서를 수집한 데이터셋이 아닙니다.',
    '30은 실제 기항문서 수가 아니라 합성 비용 레코드를 묶은 시나리오 그룹 수입니다.',
    '비용항목 의미 매핑을 평가하며 OCR·스캔 문서 복원 성능은 포함하지 않습니다.',
    '통제된 문장 템플릿과 도메인 사전을 사용하므로 실제 문서보다 쉬운 시험일 수 있습니다.',
    '예외 탐지는 결정형 통제이며 AI 의미 매핑 성능과 분리해 해석합니다.',
    '실제 검토시간과 수정률은 참여기업 PoC에서 별도로 측정해야 합니다.',
  ],
  labels: ['도선', '예선', '하역', '계선', '접안', '대리점'] as const,
  confusionMatrix: [
    [30, 0, 0, 0, 0, 0],
    [0, 24, 0, 0, 6, 0],
    [0, 0, 29, 0, 0, 1],
    [0, 0, 0, 23, 7, 0],
    [0, 0, 0, 0, 29, 1],
    [0, 0, 0, 0, 0, 30],
  ],
  classMetrics: [
    { label: '도선', precision: 1, recall: 1, f1: 1, support: 30 },
    { label: '예선', precision: 1, recall: 0.8, f1: 0.8889, support: 30 },
    { label: '하역', precision: 1, recall: 0.9667, f1: 0.9831, support: 30 },
    { label: '계선', precision: 1, recall: 0.7667, f1: 0.8679, support: 30 },
    { label: '접안', precision: 0.6905, recall: 0.9667, f1: 0.8056, support: 30 },
    { label: '대리점', precision: 0.9375, recall: 1, f1: 0.9677, support: 30 },
  ],
  sampleRows: [
    { id: 'ITEM-001-02', input: 'two tugs used · supplier billing', answer: '예선', prediction: '예선', result: '정답' },
    { id: 'ITEM-002-04', input: 'berthing attendance · ops record attached', answer: '계선', prediction: '접안', result: '오분류' },
    { id: 'ITEM-005-02', input: 'tug attendance berth shifting · service note', answer: '예선', prediction: '접안', result: '오분류' },
  ],
} as const
